# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad0cpp_conti_int <- function(w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se) {
    .Call(`_noteargis_grad0cpp_conti_int`, w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se)
}

grad0cpp_conti_noint <- function(w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se) {
    .Call(`_noteargis_grad0cpp_conti_noint`, w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se)
}

grad0cpp_multi <- function(w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se, SSr) {
    .Call(`_noteargis_grad0cpp_multi`, w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se, SSr)
}

obj0cpp_conti_int <- function(w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se) {
    .Call(`_noteargis_obj0cpp_conti_int`, w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se)
}

obj0cpp_conti_noint <- function(w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se) {
    .Call(`_noteargis_obj0cpp_conti_noint`, w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se)
}

obj0cpp_multi <- function(w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se) {
    .Call(`_noteargis_obj0cpp_multi`, w, beta, mu, rho, alpha, rho1, X, Y, white_coefs, idx_intcpt, n_resps, n_obs, n_nodes, n_coefs, Sr, Se)
}

